### ISSUE TITLE
Feature request: contentsize of document from parser

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/importer#11]
Sometimes Content-Length information is not available in the header. Maybe the parser can provide the info?

**Comment by OkkeKlein** [comment]
I noticed a DocumentLengthTagger appearing in the code (not documentation). Tested it and it works for me. Thank you.
```
   <tagger class="com.norconex.importer.handler.tagger.impl.DocumentLengthTagger"
       field="(mandatory target field)"
       overwrite="[false|true]" >
       
       <restrictTo caseSensitive="[false|true]"
               field="(name of header/metadata field name to match)">
           (regular expression of value to match)
       </restrictTo>
       <!-- multiple "restrictTo" tags allowed (only one needs to match) -->
  </tagger>
```

**Comment by essiembre** [comment]
Curious, what do you mean by "not documentation". I did forget to update this ticket if that's what you mean.  

Otherwise, that tagger is found on the [configuration](http://www.norconex.com/collectors/importer/configuration) documentation page, in the [javadoc](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DocumentLengthTagger.html), as well as the [release notes](http://www.norconex.com/collectors/importer/releases#a2.2.0-SNAPSHOT).  Considering that's still in a snapshot release, that's not bad. ;-)  Were you expecting it somewhere else?

**Comment by OkkeKlein** [comment]
I see it now. Not sure why I missed it. Looked several times. Ignore comment.

**Comment by essiembre** [comment]
The feature is now part of the new [Importer 2.2.0 stable release](http://www.norconex.com/collectors/importer/download).
