### ISSUE TITLE
Importer Fork

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/importer#2]
Hello,

I plan to create a copy of existent importer which contains some additional specific functional.

It is possible I misunderstood all importer's configuration options and creating a duplicate: needed a kind of advanced heuristics for working with DOM tree of XML/HTML documents (jsoup, or similar). I see it as a class for http-collector.

Reading importer sources I realized that they have a complex structure so I need your advice: which classes I may take as a sample, and how may I organize the project.

Thank you.

**Comment by essiembre** [comment]
If I understand you well, and if this is only for your own purpose (i.e. not for a contribution), you do not need to modify anything, but instead simply create a new class in your own project and add it to your app class path, as described [here](http://www.norconex.com/collectors/collector-http/getting-started#Extend_the_HTTP_Collector) or under "Get your workspace setup" on [this article](http://www.norconex.com/create-a-website-broken-links-checker/).  

My recommendation would be to create yourself an implementation of [IDocumentTransformer](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/IDocumentTransformer.html) if you plan on modifying the content, or [IDocumentTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/IDocumentTagger.html) if you plan on reading the content, but not modify it.  Look for abstract classes that already makes it easier to deal with text, such as AbstractCharStreamTransformer.   

In your new class, you would basically do:

* Create a DOM tree from the supplied stream/reader.
* Do what you have to do (like adding new fields to the document metadata).
* Add your new ``tagger`` or ``transformer`` class to your importer configuration, under ``preParseHandlers`` (since you probably want the raw XML/HTML... so we do this before parsing occurs).  
* Run it, you are done.

If you plan on splitting your XML into multiple records/documents, have a look at the [IDocumentSplitter](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/splitter/IDocumentSplitter.html) interface instead.  You can find an sample implementation of that one by having a look at the CsvSplitter class.

I was envisioning something along those lines for the feature request we have on HTTP Collector issue list.  The only issue I personally have with using a DOM tree is with memory and performance when dealing with very large files.  Something you should be careful about in your implementation, or consider a SAX parser instead.

It is possible I did not get perfectly what you are after.  Does that answer your question?

**Comment by AntonioAmore** [comment]
Thank you, the answer is very informative!

I plan make some DOM transformations before feeding the Document to the Importer. Is it related to IDocumentTransformer interface? 

And I want be sure the transformation happens only for HTML/XML documents. Should the check being performed inside the class?
It might be good to reject further processing/commiting of stylesheets, or a Javascripts with wrong extension, when url filter may not so effective. The typical case: caching
```
somesite.com/somejavascript.js?12345678
``` 
Mentioned above may be related to other files types and it isn't smart to write regexps for all possible combinations of extensions and caching techniques. So I decidet to use some tricks in addition to url filters and extension filters. Is there more effective way to do it?

**Comment by essiembre** [comment]
If your class extends ``AbstractCharStreamTransformer``, you can restrict which documents will go through your transformer by filtering on any field value.  For example, you can add this to your config: 
```
 <transformer class="com.your.package.your.Class">
      <restrictTo caseSensitive="false" field="document.contentType">
          text/html
      </restrictTo>
</transformer>
```

**Comment by AntonioAmore** [comment]
What if contentType isn't text/html? It skips transformation, or skip import at all?

**Comment by essiembre** [comment]
It should be only skipping that transformer.   You have the root Logger set to DEBUG?  You have to make sure you have a logger that will match your package/class.

**Comment by AntonioAmore** [comment]
Is there any mean to check were the custom transformer loaded?

Please comment my transformTextDocument I placed to previous post: Have I correctly read crawled page content and put modified content back to be used with the Importer?

**Comment by essiembre** [comment]
Maybe it is not being referenced properly.  Can you attach your full config?  What is your fully qualified class name?

Do you have errors in the logs?

You seem to be doing it right in your code above.  In case you have a logging issue, maybe using a ``System.out.println("blah");`` for now may be a way to check if it runs (other then confirming if your new content is committed of course).

**Comment by AntonioAmore** [comment]
I can confirm that committing is taking place: it is available in logs and in the database, but seems transformations aren't performed.

Here the importer's config I'm using (copied from the example which comes with collector-http):

```xml
<importer>
<transformer class="com.mypackage.MyDocumentrTransformer">
     <restrictTo caseSensitive="false" field="document.contentType">
	 text/html
    </restrictTo>

    <selectorsForDeletion>
        <selector>script</selector>
	<selector>noscript</selector>
    </selectorsForDeletion>

    <reduce>\s</reduce>
    <reduce>\n</reduce>
    <reduce>\s\n</reduce>
    <reduce>\r\n</reduce>

</transformer>

  <postParseHandlers>
     <tagger class="com.norconex.importer.handler.tagger.impl.ConstantTagger">
       <constant name="SITE">Norconex Test Site</constant>
     </tagger>
     <tagger class="com.norconex.importer.handler.tagger.impl.DeleteTagger" 
            fields="$fieldsToDelete"/>
  </postParseHandlers>
</importer> 
```

**Comment by essiembre** [comment]
Your transformer, along with any other handlers you create or use, all need to go either within a ``preParseHandlers`` or ``postParseHandlers`` tags.  You can find that structure documented [here](http://www.norconex.com/collectors/importer/configuration).  That would explain why it is not invoked.

Also, the ``selectorsForDeletion`` and ``reduce`` tags in your transformer are custom tags you wrote for your custom transformer?  Just making sure by asking, since you did not post your complete code.

**Comment by AntonioAmore** [comment]
Selectors are configuration for my custom code, ```<reduce>``` has similar to ```ReduceConsecutivesTransformer``` logic - I copied it.

Thanks, a lot, I'll check docs you provided nearest time and provide feedback here.

**Comment by AntonioAmore** [comment]
I moved ```<transformer>``` to the bottom of ```<postParseHandlers>``` section and it works, thank you.

Then I have another problem: committed text looks like
```
13 13 Skip to main content13 1313 131313131313 13 13 1313 13 1313 13 13 1313 Login1313 13 13 Username *13 13131313 Password *13 
```

```java
public class MyDocumentTransformer extends AbstractCharStreamTransformer implements IXMLConfigurable {
...
@Override
    protected void transformTextDocument(String string, Reader reader, Writer writer, ImporterMetadata im, boolean bln) throws IOException {
        
        /*
         * Read content
         */
        BufferedReader in = new BufferedReader(reader);
        StringBuilder page = new StringBuilder();        
        String line = null;
        
        while((line = in.readLine()) != null ) {
            page.append(line).append(LINE_SEPARATOR);
        }
...
        page.toString().SomeOperations();
```

I used ```AbstractCharStreamTransformer``` because want apply your advice about non-text/html restriction, upper in this issue.

Seems my current Java code reads ```\n``` symbol as a sequence of chars '1' and '3'. May you give me advice how to handle ```\n\r\s``` and others without dirty hack, with clean and maintainable code?

**Comment by essiembre** [comment]
It is hard for me to tell as I do not know how you have integrated the reduce tags.   I can suggest one thing: Use the existing ``ReduceConsecutivesTransformer`` after your own tags.  It is important to know you can have as many handlers as you want, and they will processed in the order you define them. 

So I suggest you try:
```xml
...
<postParseHandlers>
    <transformer class="com.mypackage.MyDocumentrTransformer">
        <selectorsForDeletion>
            <selector>script</selector>
            <selector>noscript</selector>
        </selectorsForDeletion>
        <restrictTo caseSensitive="false" field="document.contentType">
            text/html
        </restrictTo>
    </transformer>
    <transformer class="com.norconex.importer.handler.transformer.impl.ReduceConsecutivesTransformer">
        <reduce>\s</reduce>
        <reduce>\n</reduce>
        <reduce>\s\n</reduce>
        <reduce>\r\n</reduce>
        <restrictTo caseSensitive="false" field="document.contentType">
            text/html
        </restrictTo>
  </transformer>
<postParseHandlers>
...
```
If you still have issues with what is being written out, it may also be a problem with in code.  To confirm that, you can try removing/commenting your own transformer and check whether the ``ReduceConsecutivesTransformer`` does its job properly.

**Comment by AntonioAmore** [comment]
Thank you, it should work well. Are they called in the order they are mentioned in config?

**Comment by essiembre** [comment]
Yes, the order is respected.  I suggest you try with the snapshot release, as a fix has been made on a bug that could "possibly" affect you.  See the bottom of this ticket for how to get it: https://github.com/Norconex/collector-http/issues/55

**Comment by AntonioAmore** [comment]
Thank you. I haven't detected any significant change, but, probably, find it after longer test,

**Comment by essiembre** [comment]
Are things OK with this issue now?

**Comment by AntonioAmore** [comment]
Thanks a lot. Seems everything is working well, and all my ideas are implemented with custom transformer and set of transformers from the standard importer.

**Comment by essiembre** [comment]
Excellent.  Closing.
