### ISSUE TITLE
How to work only on elements splitted by a DOMSplitter

### ISSUE THREAD

**Issue by liar666** [Norconex/importer#31]
Hi,

I'm trying to parse XML files (from https://pairbulkdata.uspto.gov/) in which patents are described. 

In order to parse/import these files, I use a DOMSplitter to separate the data for each patent, then a DOMTagger to extract information for each patent.

Unfortunately, more data than those present in the XML file is submitted to my committer. There is some redundancy.

I think the problem comes from the fact that **both** the whole file **and** the splitted parts get parsed/imported.

Since I've noticed some information is added by the DOMSplitter to the "document.reference", I've tried to add a filter to my DOMTagger, so that my crawler treats only the splitted elements. More specifically, I used:
```
           <tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">
            <filter class="com.norconex.importer.handler.filter.impl.RegexMetadataFilter"
                    onMatch="include" field="document.reference" >
              !html
            </filter>

```
Unfortunately, this does not work.

Is there any simple way to make a (DOM)Tagger work only on splitted elements from a (DOM)Splitter?

**Comment by essiembre** [comment]
Your analysis or your problem seems spot on.  Your solution too... so it is probably just a mis-config.

From your config snippet, it seems you have embedded ``filter`` into ``tagger``, is that accurate?  That would explain why.  You need to have them one the same level, one AFTER the other.

You can exclude the "parent" (document that was split) based on document.reference, but I am not sure the regular expression you have in it will match anything. If you want to exclude html then you probably want the filter to be ``onMatch="exclude"`` and your pattern something like this: ``.*\.html``.

**Comment by liar666** [comment]
Hi,

It's strange, I'm almost sure I took my inspiration from a previous code we were discussing, where the filter was inside the tagger...

Whatever, thanks for the response, moving the filter outside the tagger and playing a bit with the regexes made my crawler work like a charm!

**Comment by essiembre** [comment]
You are probably mixing it up with the ``<restrictTo ...> which can be embedded inside most taggers to make sure it applies to only certain documents.  

Glad you made it work!
