### ISSUE TITLE
metadata extraction on News Site

### ISSUE THREAD

**Issue by angelo337** [Norconex/importer#37]
hi there
I am trying to crawl a News Site, but I am unable to extract information from Metadata in the pages there is no metadata on my Solr after I crawl some 50 pages, and no evidence of why is that, I see all content is in there and Metadata of the server and crawler but now from this pages it self, could you please point me out some resources of links to extract that type of data?
an example of metadata is like this:

``` xml
<meta property="og:type" content="article" />
```

or

``` xml
<meta property="ps:publishDate" content="2004/01/19" />
```

or 

``` xml
<meta property="twitter:url" content="....">
```

thanks

**Comment by essiembre** [comment]
What type of pages are you referring to?  Because metadata from standard documents is extracted automatically.  The tags you list as examples look like HTML meta tags, but they are not of proper format (see http://www.w3schools.com/tags/tag_meta.asp).  The format should be:
```xml
<meta name="og:type" content="article">
```

If you are crawling custom XML files, you may have to extract the data yourself.  For this, I suggest you use some of the classes offered in the importer module, like the [DOMTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DOMTagger.html) or the [TextPatternTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/TextPatternTagger.html).  Use them as "preParseHandlers" in your [importer config](https://www.norconex.com/collectors/importer/configuration) section.

**Comment by essiembre** [comment]
Closing due to lack of feedback.  Please re-open if you have any updates to share.
