### ISSUE TITLE
Irregular behaviour of TextBetweenTagger

### ISSUE THREAD

**Issue by Betongsuggan** [Norconex/importer#4]
I'm using TextBetweenTagger in order to acquire HTML code from crawled pages. The configuration looks like:

    <preParseHandlers>
        <tagger class="com.norconex.importer.handler.tagger.impl.TextBetweenTagger" inclusive="true">
            <textBetween name="rawhtml">
                <start>^.*</start>
                <end>.*$</end>
            </textBetween>
        </tagger>
    </preParseHandlers>

However, this has put the crawler in an inconsequent behaviour. Upon crawling ~4k webpages, 10-150 of them have their HTML split up into several rawhtml fields, instead of being put in one field, as the majority of the documents has.

It is arbitrary which documents which gets this behaviour from each crawl, and the number of broken documents vary as well.

Any other way you would suggest to acquire the unparsed HTML content?

EDIT: Version 2.0.1 is being used.

**Comment by essiembre** [comment]
If I understand you well, the only scenario I can think of right now where something like this could happen and the importer is the cause, is when memory is getting lower.  Are some of these files large?  Or are you doing *many* threads at once so that memory consumption can be higher?   See, the TextBetweenTagger is a subclass of AbstractStringTagger which will split text documents when it witnessed memory becomes less available.  You can find the exact memory-handling logic [here](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/AbstractStringTagger.html).

Possible workarounds include:
1. Increasing JVM memory.  You can modify the batch or shell script to [add JVM memory arguments](http://stackoverflow.com/questions/6452765/how-to-increase-heap-size-of-jvm).
2. If you are ok with Java, you can create your own tagger which would extend a lowel-level class, like [AbstractCharStreamTagger](), who does not stick anything in memory, giving you a character stream to deal with instead.
3. See if reducing your number of threads can help (e.g. concurrently processing 20 documents at once takes more memory than if it was is 5).

The fact that you say it happens after 4K only is more concerning.  Either you are hitting big documents at that point, or it may suggest a memory leak.  The later would be annoying as we benchmarked with over a million docs crawled ans we saw stable memory usage... so it may be tricky to find.  

If you see no improvements after trying items 1 and 3 above, the problem might be entirely different (i.e. have nothing to do with memory) and a full copy of your config may help in trying to reproduce.

**Comment by essiembre** [comment]
I just realized... you are sticking ALL of the page content into a field?  That will eat up more memory for sure, and the reason why the content is usually left as a stream and considered differently by the Importer (i.e. not a field).   May I ask what you are trying to achieve by doing this?  Because there might be better ways.  For instance, most Committer implementations offers to stick the content in a target field of your choice (like a Solr "fulltext" field).    If you can provide more details on your end-goal here, I might be able to help you more.

**Comment by Betongsuggan** [comment]
Thanks for quick answer!

I have tried to run the crawler single threaded as well, but with no improvement.

Your theory about the memory consumption sounds good. Will implement a lighter tagger using the AbstractCharStreamTagger you suggested to see if that will lessen the load.

The reason for this verbose way of committing information is that I have another processing step after the crawler in which we cache content before sending it to Solr. By doing this I decrease the number of crawls needed in this implementation step, in case I miss some processing steps.

The number of 4k documents is just the number of webpages on the target sites. I can't say for sure after exactly how many documents this error starts to occur I'm afraid.

**Comment by essiembre** [comment]
Are using one of [Norconex Collectors](http://www.norconex.com/collectors/) as well?  Because they know what has already been crawl or not and can help you there as well.  They also offer to save a copy of every documents "collected".  They also allow you to implement "post import processors" so you can do whatever you want with a document after it has been imported, before it is committed (for HTTP crawls as an example, you can find more details in this [config overview](http://www.norconex.com/collectors/collector-http/configuration)).

It may or may not apply to what you are trying to achieve... just sharing :-)

I'd like to hear on your progress.

**Comment by Betongsuggan** [comment]
Thanks for the information! I will update when I have tried out a new tagger.

**Comment by Betongsuggan** [comment]
Hi, sorry for the late respons. 

The problem was indeed what you suggested, a memory issue, and the classes behave as intended and documentet in AbstactStringTagger.

In the end it was a matter of bumping the memory a notch and reducing the queue and size of the commit batch which seems to solve it for this solution. 

I'll mark this as closed for this issue and I thank you for a fast respons.
