### ISSUE TITLE
Difference between content type fields

### ISSUE THREAD

**Issue by danizen** [Norconex/importer#46]
I now have installed Kibana on another host, and it is proving fruitful in allowing met to explore my data.   I find it interesting that the `KeepOnlyTagger` allows multiple cases through of field, but these are not normalized by Elasticsearch!

This is leading to a good amount of testing, and I wonder:

* What regexp flags are used on `<fromFieldsRegex>` in the MergeTagger, and in general?
* Is there a way (other than `ScriptTagger`) to remove empty fields?
* What are the differences between `Content-Type`, `Content-Type-Hint` and `document.contentType`?   If I plan to keep one, which would you suggest?

**Comment by danizen** [comment]
Follow-up question:
* I have 5 documents with an `URL` field and no `url` field.   That means that they had no `document.reference` field, because I can typically rename it to `url`.    However, Tika clearly has extracted text from these documents.  What could it mean?

**Comment by essiembre** [comment]
- **MergeTagger:** no flags are set.  Java default Regex settings. 
- **Remove empty fields:** You can use the ``DeleteTagger`` with this ``<fieldsRegex>^\s*$</fieldsRegex>``. Remove the \s* if you do not want to consider white spaces.
- **Content-Type:**  Fields starting with ``collector.`` are set by the Collector, fields that start with ``document.`` are set by the Importer.  Everything else is normally set by you, HTTP headers, or fields extracted from the document itself.   Depends on what you are after, but I personally recommend ``document.contentType`` since you are guaranteed it is always set, no matter the Collector or the file (as long as it is properly parsed by the Importer.

About your URLs, I am not sure I understand what you are asking.  ``document.reference`` should always be set by the importer (unless you explicitly remove/rename it).

About field case sensitivity: You can use the ``CharacterCaseTagger`` to adjust the case of all your fields before they are committed.

**Comment by danizen** [comment]
Thank you, Pascal, very coherent, simple answers.

> About your URLs, I am not sure I understand what you are asking. `document.reference` should always be set by the importer (unless you explicitly remove/rename it).

I think what happened is that Tika discovered in these PPT and ZIP files an `URL` meta-data field, and so my attempt to rename `document.reference` to `url` did not take.   Now it is has `overwrite="true"`, so if that was it, it will work.   It was only 5 out of ~60k documents.
