### ISSUE TITLE
URL building for child elements

### ISSUE THREAD

**Issue by sveba** [Norconex/importer#55]
https://github.com/Norconex/importer/blob/49e9da592e6e0c373b138a6da1c544bfddc7e657/norconex-importer/src/main/java/com/norconex/importer/handler/splitter/impl/DOMSplitter.java#L172

IMO the URL should be `parent#!childEmbedRef` and not `parent!#childEmbedRef`

**Comment by essiembre** [comment]
The ``!`` character is used to separate parents and children.  The ``#`` is actually is part of the child reference, which is a unique "CSS selector" created by JSoup (the library used by DOMSplitter).  It is not part of the parent reference so it does not belong there.

Feel free to re-open if you are experiencing issues.

**Comment by sveba** [comment]
Hmm ok. The child reference is not usable in that case as the browser can not understand that syntax.

Is there any way to alter the child URL before it is being passed to the commiter?

**Comment by essiembre** [comment]
The reference does not have for objective to work in a browser.  It is equivalent to a unique ID and does not have to conform to a URL.  Based its source, it can be anything as long as it is unique to a document (URL, file path, database primary key, etc). 

If you want to build a URL for usage in a browser for embedded documents, I suggest you use a custom field to store the URL how you want it.   Each element is available separately:
```
document.embedded.parent.reference=http://www.example.com/parent.html
document.embedded.reference=#embeddedChild
```
One approach could be to combine the embedded references if present:
```xml
    <tagger class="com.norconex.importer.handler.tagger.impl.MergeTagger">
      <merge toField="my_embedded_url" singleValue="true">
        <fromFields>document.embedded.parent.reference,document.embedded.reference</fromFields>
      </merge>
    </tagger>
```

In your specific use case, what you want to do can work in browsers because the elements that are split have an ``id`` attribute.  It will likely not work for cases of elements not having the ``id`` attribute since the embedded reference returned would look like this:  
```
html > body > div.people > div.person\:nth-child(2)
```
