### ISSUE TITLE
Import only certain text from HTML file

### ISSUE THREAD

**Issue by HappyCustomers** [Norconex/importer#87]
Hi,

I want to import only certain data from the webpage which I am crawling. This data exists between the body tag of the HTML page

```xml
   <span class="name"> The ACME Business </span>
   <span class="city">Bangalore</span>
   <span class="url address">www.acme.com</span>
```   

I want to the extract above values into respective field names into database.

I tried the following configuration in preParseHandlers and it is not working

```xml  
    <tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">
      <dom selector=""url address" toField="url" />
      <dom selector="span.name"  toField="name" overwrite="false" matchBlanks="false" />
    </tagger>							  
```
Which one should I use DOMTagger or TextPatternTagger? 	
Can U please proved the configuration example for the above?

Thank You

**Comment by essiembre** [comment]
You have an XML syntax error in the sample you posted (an extra double-quote on the first selector).
This one works for me:
```
<dom selector="span.name"  toField="name"/>
```
For the URL one, if you can use only one of the classes if you like:
```
<dom selector="span.url"  toField="url"/>
```
If you have to match the two classes, this is a syntax that works for me:
```
<dom selector="span[class='url address']"  toField="url"/>
```
Refer to [JSoup documentation](https://jsoup.org/cookbook/extracting-data/selector-syntax) for syntax options.

**Comment by HappyCustomers** [comment]
Thanks for the quick response. Actually I had missed adding the fields in PostparseHandlers. 

I have few more issues where certain data is not getting extracted, will try to resolve on my own else will send u then email with config document.
Thanks once again

**Comment by HappyCustomers** [comment]
Dear Mr. Pascal,

I have sent you the config file by email for your review. one of the fields is not getting extracted. Can you please help

Thank you

**Comment by essiembre** [comment]
From the DOM selector and the two URLs you provided by email, I can tell the field you want is not extracted simply because they are not on the page.  If you view the source for the page, you will not find it.

It seems that the field is dynamically generated using Javascript.  The HTTP Collector does not have a built-in Javascript-rendering engine.  To crawl javascript-generated content, you can use an external installation of PhantomJS.  Have a look at [PhantomJSDocumentFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html).

**Comment by HappyCustomers** [comment]
Thanks for the solution. Is there any sample config to extract dynamic content using PhantomJs?

**Comment by HappyCustomers** [comment]
I am closing this as I am able to extract static Content from webpages Using DOMTagger. For Dynamic Content trying PhantomJS.
